# Generated by Django 2.1 on 2018-08-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20180806_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='consume_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='record',
            name='liquid_amount',
        ),
        migrations.RemoveField(
            model_name='record',
            name='stool_count',
        ),
        migrations.RemoveField(
            model_name='record',
            name='urine_amount',
        ),
        migrations.AddField(
            model_name='record',
            name='io_type',
            field=models.PositiveIntegerField(choices=[(1, 'Input'), (2, 'Output')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='record_type',
            field=models.PositiveIntegerField(choices=[(1, '수분'), (2, '식사'), (3, '소변'), (4, '대변')], default=1),
            preserve_default=False,
        ),
    ]
