# Generated by Django 2.1 on 2018-08-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20180809_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.PositiveIntegerField(choices=[(1001, '수분'), (1002, '식사'), (2001, '소변'), (2002, '대변')]),
        ),
    ]
