# Generated by Django 2.1 on 2018-08-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_foodlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='foot_type',
            field=models.PositiveIntegerField(choices=[(3000, '고체'), (4000, '액체')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='io_type',
            field=models.PositiveIntegerField(choices=[(1000, 'Input'), (2000, 'Output')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.PositiveIntegerField(choices=[(1100, '수분'), (1200, '식사'), (2100, '소변'), (2200, '대변')]),
        ),
    ]
