# Generated by Django 2.1 on 2018-08-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20180813_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlist',
            name='foot_type',
        ),
        migrations.AlterField(
            model_name='record',
            name='io_type',
            field=models.PositiveIntegerField(choices=[(1, 'Input'), (2, 'Output')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.PositiveIntegerField(choices=[(1, '수분'), (2, '식사')]),
        ),
    ]
