# Generated by Django 2.1 on 2018-08-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20180803_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='birth',
            field=models.DateField(),
        ),
    ]
