# Generated by Django 2.1 on 2018-08-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20180803_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
