# Generated by Django 2.1 on 2018-08-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20180803_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='room',
            field=models.CharField(default='A1000', max_length=10),
            preserve_default=False,
        ),
    ]
