# Generated by Django 2.1 on 2018-08-15 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_information_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='patient',
        ),
    ]
